name: puente_humano
description: "Un puente humano para que los libros lleguen a donde más se necesitan"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Supabase
  supabase_flutter: ^2.8.0
  
  
  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  
  # State Management
  provider: ^6.1.2
  
  # Navigation
  go_router: ^14.2.9
  
  # Maps & Location
  google_maps_flutter: ^2.9.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  
  # QR & Image
  qr_flutter: ^4.1.0
  mobile_scanner: ^4.0.1
  image_picker: ^1.1.2
  
  # Network & Storage
  http: ^1.2.2
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  
  # Chat & Real-time
  web_socket_channel: ^2.4.0
  
  # Utils
  intl: ^0.20.2
  uuid: ^4.5.1

  crypto: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  supabase: any
flutter:
  uses-material-design: true