name: Build iOS for Testing

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.1'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build iOS (no codesign)
      run: |
        flutter build ios --${{ github.event.inputs.build_type }} --no-codesign
    
    - name: Create IPA archive
      run: |
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r ../../../PuenteHumano-${{ github.event.inputs.build_type }}.ipa Payload
        
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v3
      with:
        name: PuenteHumano-iOS-${{ github.event.inputs.build_type }}
        path: PuenteHumano-${{ github.event.inputs.build_type }}.ipa
        retention-days: 7